Update faq.md
liberty-mp/wiki pull request #66
Opened 2023-04-04 23:07 UTC by LazarAndrei1106

2023-04-05 09:54 UTC, leonardssh requested changes

2023-04-05 09:54 UTC, leonardssh commented on faq.md
> +Pentru a îți asocia contul din joc cu o adresa de E-mail trebuie să te autentifici pe [**UCP**](https://ucp.liberty.mp/), să apeși pe numele tău din dreapta-sus, apoi să selectezi **Settings**.
```suggestion
Pentru a îți asocia contul din joc cu o adresă de E-mail trebuie să te autentifici pe [**UCP**](https://ucp.liberty.mp/), să apeși pe numele tău din dreapta-sus, apoi să selectezi **Settings**. 
```

2023-04-05 09:54 UTC, leonardssh commented on faq.md
> +Ulterior, apasă pe opționea **Set** din dreptul textlui **Email address**. Introduci adresa de email dorita apoi selectezi **Set email**. O sa primești un mail de confirmare pe adresa de email introd
```suggestion
Ulterior, apasă pe opțiunea **Set** din dreptul textului **Email address**. Introduci adresa de email dorită apoi selectezi **Set email**. O sa primești un mail de confirmare pe adresa de email introdusă.
```

2023-04-05 09:54 UTC, leonardssh commented on faq.md
> +Dupa accesarea linkului de confirmare, o să fii redirecționat înapoi pe [**UCP**](https://ucp.liberty.mp/) unde îți va fi afișat în stânga-jos un mesaj prin care te informează că acțiunea de asociere
```suggestion
După accesarea linkului de confirmare, o să fii redirecționat înapoi pe [**UCP**](https://ucp.liberty.mp/) unde îți va fi afișat în stânga-jos un mesaj prin care te informează că acțiunea de asociere a avut succes.
```

2023-04-05 09:54 UTC, leonardssh commented on faq.md
> +<Image src="https://im5.ezgif.com/tmp/ezgif-5-9958a75010.gif" alt="Link Email" />
The gif doesn't work.

2023-04-05 09:54 UTC, leonardssh commented on faq.md
> +Daca mail-ul de confirmare nu apare in **Inbox** sugeram sa il cauti in **Spam**.
```suggestion
Dacă mail-ul de confirmare nu apare in **Inbox**, îți sugerăm să-l cauți in **Spam**.
```

2023-04-05 23:52 UTC, LazarAndrei1106 commented on faq.md
> +<Image src="https://im5.ezgif.com/tmp/ezgif-5-9958a75010.gif" alt="Link Email" />
Nu cred :( la mine mergea.

2023-04-07 20:18 UTC, leonardssh approved these changes

2023-04-07 20:18 UTC, leonardssh commented
This PR needs a GIF.

2023-04-11 23:05 UTC, closed without merging